#!/bin/bash
set -u; set -e

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/_a3"

hg_repo && {
    hg addremove "$@"
    hg ci "$@" -m ...
    exit
}

git_repo && {
    git add .
    git commit -am ...
    exit
}

echo "= aci: no repo here."
