#!/bin/bash
set -u; set -e

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/_a3"

hg_repo && {
    hg ci "$@" -m ...
    exit
}

git_repo && {
    git ci -am ...
    exit
}

echo "= ci: no repo here."
