#!/bin/bash
set -u; set -e

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/_a3"

hg_repo && {
    die "= $(basename "$0"): not implemented."
}

git_repo && {
    git push "$1" --delete "$2"
    exit
}

echo "= $(basename "$0"): no repo here."
